# give sudo permissions to Travis.
sudo: required

# state that Docker must be installed on the Travis instance.
services:
  - docker

before_install:
  # setting up GKE on the Travis instance.

  # install Google Cloud SDK CLI on the Travis instance.
  - curl https://sdk.cloud.google.com | bash > /dev/null;

  # apply the SDK configuration to the Travis shell.
  - source $HOME/google-cloud-sdk/path.bash.inc

  # install the latest version of kubectl on the Travis instance.
  - gcloud components update kubectl

  # activating an account so that Travis can interact with GKE; "service-account.json" has the account credentials.
  - gcloud auth activate-service-account --key-file service-account.json

  # decrypting the credentials uploaded to Travis to it can interact with GKE.
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
